<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/MEDICAL_EXAMINATION.php");
	include("$currDir/MEDICAL_EXAMINATION_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('MEDICAL_EXAMINATION');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "MEDICAL_EXAMINATION";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`MEDICAL_EXAMINATION`.`Medical_Examination_ID`" => "Medical_Examination_ID",
		"`MEDICAL_EXAMINATION`.`First_name`" => "First_name",
		"`MEDICAL_EXAMINATION`.`Middle_name`" => "Middle_name",
		"`MEDICAL_EXAMINATION`.`Last_name`" => "Last_name",
		"`MEDICAL_EXAMINATION`.`Name_of_Medical_officer`" => "Name_of_Medical_officer",
		"if(`MEDICAL_EXAMINATION`.`Examinaton_date`,date_format(`MEDICAL_EXAMINATION`.`Examinaton_date`,'%m/%d/%Y'),'')" => "Examinaton_date",
		"`MEDICAL_EXAMINATION`.`Result`" => "Result",
		"`MEDICAL_EXAMINATION`.`Remark`" => "Remark",
		"`MEDICAL_EXAMINATION`.`Place_of_Examination`" => "Place_of_Examination",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`MEDICAL_EXAMINATION`.`Medical_Examination_ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`MEDICAL_EXAMINATION`.`Examinaton_date`',
		7 => 7,
		8 => 8,
		9 => 9,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`MEDICAL_EXAMINATION`.`Medical_Examination_ID`" => "Medical_Examination_ID",
		"`MEDICAL_EXAMINATION`.`First_name`" => "First_name",
		"`MEDICAL_EXAMINATION`.`Middle_name`" => "Middle_name",
		"`MEDICAL_EXAMINATION`.`Last_name`" => "Last_name",
		"`MEDICAL_EXAMINATION`.`Name_of_Medical_officer`" => "Name_of_Medical_officer",
		"if(`MEDICAL_EXAMINATION`.`Examinaton_date`,date_format(`MEDICAL_EXAMINATION`.`Examinaton_date`,'%m/%d/%Y'),'')" => "Examinaton_date",
		"`MEDICAL_EXAMINATION`.`Result`" => "Result",
		"`MEDICAL_EXAMINATION`.`Remark`" => "Remark",
		"`MEDICAL_EXAMINATION`.`Place_of_Examination`" => "Place_of_Examination",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`MEDICAL_EXAMINATION`.`Medical_Examination_ID`" => "MEdical_Examination ID",
		"`MEDICAL_EXAMINATION`.`First_name`" => "Fname",
		"`MEDICAL_EXAMINATION`.`Middle_name`" => "Mname",
		"`MEDICAL_EXAMINATION`.`Last_name`" => "Last name",
		"`MEDICAL_EXAMINATION`.`Name_of_Medical_officer`" => "Medical Officer Name",
		"`MEDICAL_EXAMINATION`.`Examinaton_date`" => "Examinaton date",
		"`MEDICAL_EXAMINATION`.`Result`" => "Result",
		"`MEDICAL_EXAMINATION`.`Remark`" => "Remark",
		"`MEDICAL_EXAMINATION`.`Place_of_Examination`" => "Place of Examination",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`MEDICAL_EXAMINATION`.`Medical_Examination_ID`" => "Medical_Examination_ID",
		"`MEDICAL_EXAMINATION`.`First_name`" => "First_name",
		"`MEDICAL_EXAMINATION`.`Middle_name`" => "Middle_name",
		"`MEDICAL_EXAMINATION`.`Last_name`" => "Last_name",
		"`MEDICAL_EXAMINATION`.`Name_of_Medical_officer`" => "Name_of_Medical_officer",
		"if(`MEDICAL_EXAMINATION`.`Examinaton_date`,date_format(`MEDICAL_EXAMINATION`.`Examinaton_date`,'%m/%d/%Y'),'')" => "Examinaton_date",
		"`MEDICAL_EXAMINATION`.`Result`" => "Result",
		"`MEDICAL_EXAMINATION`.`Remark`" => "Remark",
		"`MEDICAL_EXAMINATION`.`Place_of_Examination`" => "Place_of_Examination",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`MEDICAL_EXAMINATION` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "MEDICAL_EXAMINATION_view.php";
	$x->RedirectAfterInsert = "MEDICAL_EXAMINATION_view.php?SelectedID=#ID#";
	$x->TableTitle = "MEDICAL EXAMINATION";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`MEDICAL_EXAMINATION`.`Medical_Examination_ID`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("MEdical_Examination ID", "Fname", "Mname", "Last name", "Medical Officer Name", "Examinaton date", "Result", "Remark", "Place of Examination");
	$x->ColFieldName = array('Medical_Examination_ID', 'First_name', 'Middle_name', 'Last_name', 'Name_of_Medical_officer', 'Examinaton_date', 'Result', 'Remark', 'Place_of_Examination');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/MEDICAL_EXAMINATION_templateTV.html';
	$x->SelectedTemplate = 'templates/MEDICAL_EXAMINATION_templateTVS.html';
	$x->TemplateDV = 'templates/MEDICAL_EXAMINATION_templateDV.html';
	$x->TemplateDVP = 'templates/MEDICAL_EXAMINATION_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MEDICAL_EXAMINATION`.`Medical_Examination_ID`=membership_userrecords.pkValue and membership_userrecords.tableName='MEDICAL_EXAMINATION' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `MEDICAL_EXAMINATION`.`Medical_Examination_ID`=membership_userrecords.pkValue and membership_userrecords.tableName='MEDICAL_EXAMINATION' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`MEDICAL_EXAMINATION`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: MEDICAL_EXAMINATION_init
	$render=TRUE;
	if(function_exists('MEDICAL_EXAMINATION_init')) {
		$args=array();
		$render=MEDICAL_EXAMINATION_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: MEDICAL_EXAMINATION_header
	$headerCode='';
	if(function_exists('MEDICAL_EXAMINATION_header')) {
		$args=array();
		$headerCode=MEDICAL_EXAMINATION_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: MEDICAL_EXAMINATION_footer
	$footerCode='';
	if(function_exists('MEDICAL_EXAMINATION_footer')) {
		$args=array();
		$footerCode=MEDICAL_EXAMINATION_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>