<?php
// This script and data application were generated by AppGini 5.82
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Shortlisted_Applicant_Details.php");
	include("$currDir/Shortlisted_Applicant_Details_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Shortlisted_Applicant_Details');
	if(!$perm[0]) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Shortlisted_Applicant_Details";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Shortlisted_Applicant_Details`.`Serial_Number`" => "Serial_Number",
		"if(`Shortlisted_Applicant_Details`.`Shortlist_date`,date_format(`Shortlisted_Applicant_Details`.`Shortlist_date`,'%m/%d/%Y'),'')" => "Shortlist_date",
		"`Shortlisted_Applicant_Details`.`First_Name`" => "First_Name",
		"`Shortlisted_Applicant_Details`.`Middle_Name`" => "Middle_Name",
		"`Shortlisted_Applicant_Details`.`Last_Name`" => "Last_Name",
		"`Shortlisted_Applicant_Details`.`Level_of_Education`" => "Level_of_Education",
		"if(`Shortlisted_Applicant_Details`.`DOB`,date_format(`Shortlisted_Applicant_Details`.`DOB`,'%m/%d/%Y'),'')" => "DOB",
		"`Shortlisted_Applicant_Details`.`Age`" => "Age",
		"`Shortlisted_Applicant_Details`.`District_of_Origin`" => "District_of_Origin",
		"`Shortlisted_Applicant_Details`.`Recruitment_centre`" => "Recruitment_centre",
		"`Shortlisted_Applicant_Details`.`Gender`" => "Gender",
		"`Shortlisted_Applicant_Details`.`Telephone_Contact`" => "Telephone_Contact",
		"`Shortlisted_Applicant_Details`.`Religion`" => "Religion",
		"`Shortlisted_Applicant_Details`.`Nationality`" => "Nationality",
		"`Shortlisted_Applicant_Details`.`NIN`" => "NIN",
		"`Shortlisted_Applicant_Details`.`Tribe`" => "Tribe",
		"`Shortlisted_Applicant_Details`.`Special_attribute`" => "Special_attribute",
		"`Shortlisted_Applicant_Details`.`OLevel_School`" => "OLevel_School",
		"`Shortlisted_Applicant_Details`.`English_Grade`" => "English_Grade",
		"`Shortlisted_Applicant_Details`.`Math_Grade`" => "Math_Grade",
		"`Shortlisted_Applicant_Details`.`Description`" => "Description",
		"`Shortlisted_Applicant_Details`.`Total_Mark`" => "Total_Mark",
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Shortlisted_Applicant_Details`.`Serial_Number`',
		2 => '`Shortlisted_Applicant_Details`.`Shortlist_date`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`Shortlisted_Applicant_Details`.`DOB`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Shortlisted_Applicant_Details`.`Serial_Number`" => "Serial_Number",
		"if(`Shortlisted_Applicant_Details`.`Shortlist_date`,date_format(`Shortlisted_Applicant_Details`.`Shortlist_date`,'%m/%d/%Y'),'')" => "Shortlist_date",
		"`Shortlisted_Applicant_Details`.`First_Name`" => "First_Name",
		"`Shortlisted_Applicant_Details`.`Middle_Name`" => "Middle_Name",
		"`Shortlisted_Applicant_Details`.`Last_Name`" => "Last_Name",
		"`Shortlisted_Applicant_Details`.`Level_of_Education`" => "Level_of_Education",
		"if(`Shortlisted_Applicant_Details`.`DOB`,date_format(`Shortlisted_Applicant_Details`.`DOB`,'%m/%d/%Y'),'')" => "DOB",
		"`Shortlisted_Applicant_Details`.`Age`" => "Age",
		"`Shortlisted_Applicant_Details`.`District_of_Origin`" => "District_of_Origin",
		"`Shortlisted_Applicant_Details`.`Recruitment_centre`" => "Recruitment_centre",
		"`Shortlisted_Applicant_Details`.`Gender`" => "Gender",
		"`Shortlisted_Applicant_Details`.`Telephone_Contact`" => "Telephone_Contact",
		"`Shortlisted_Applicant_Details`.`Religion`" => "Religion",
		"`Shortlisted_Applicant_Details`.`Nationality`" => "Nationality",
		"`Shortlisted_Applicant_Details`.`NIN`" => "NIN",
		"`Shortlisted_Applicant_Details`.`Tribe`" => "Tribe",
		"`Shortlisted_Applicant_Details`.`Special_attribute`" => "Special_attribute",
		"`Shortlisted_Applicant_Details`.`OLevel_School`" => "OLevel_School",
		"`Shortlisted_Applicant_Details`.`English_Grade`" => "English_Grade",
		"`Shortlisted_Applicant_Details`.`Math_Grade`" => "Math_Grade",
		"`Shortlisted_Applicant_Details`.`Description`" => "Description",
		"`Shortlisted_Applicant_Details`.`Total_Mark`" => "Total_Mark",
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Shortlisted_Applicant_Details`.`Serial_Number`" => "S/No",
		"`Shortlisted_Applicant_Details`.`Shortlist_date`" => "Shortlist date",
		"`Shortlisted_Applicant_Details`.`First_Name`" => "First Name",
		"`Shortlisted_Applicant_Details`.`Middle_Name`" => "Middle Name",
		"`Shortlisted_Applicant_Details`.`Last_Name`" => "Last Name",
		"`Shortlisted_Applicant_Details`.`Level_of_Education`" => "Level of Education",
		"`Shortlisted_Applicant_Details`.`DOB`" => "DOB",
		"`Shortlisted_Applicant_Details`.`Age`" => "Age",
		"`Shortlisted_Applicant_Details`.`District_of_Origin`" => "District of Origin",
		"`Shortlisted_Applicant_Details`.`Recruitment_centre`" => "Recruitment centre",
		"`Shortlisted_Applicant_Details`.`Gender`" => "Gender",
		"`Shortlisted_Applicant_Details`.`Telephone_Contact`" => "Telephone Contact",
		"`Shortlisted_Applicant_Details`.`Religion`" => "Religion",
		"`Shortlisted_Applicant_Details`.`Nationality`" => "Nationality",
		"`Shortlisted_Applicant_Details`.`NIN`" => "NIN",
		"`Shortlisted_Applicant_Details`.`Tribe`" => "Tribe",
		"`Shortlisted_Applicant_Details`.`Special_attribute`" => "Special attribute",
		"`Shortlisted_Applicant_Details`.`OLevel_School`" => "OLevel School",
		"`Shortlisted_Applicant_Details`.`English_Grade`" => "English Grade",
		"`Shortlisted_Applicant_Details`.`Math_Grade`" => "Math Grade",
		"`Shortlisted_Applicant_Details`.`Description`" => "Description",
		"`Shortlisted_Applicant_Details`.`Total_Mark`" => "Total Mark",
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Shortlisted_Applicant_Details`.`Serial_Number`" => "Serial_Number",
		"if(`Shortlisted_Applicant_Details`.`Shortlist_date`,date_format(`Shortlisted_Applicant_Details`.`Shortlist_date`,'%m/%d/%Y'),'')" => "Shortlist_date",
		"`Shortlisted_Applicant_Details`.`First_Name`" => "First_Name",
		"`Shortlisted_Applicant_Details`.`Middle_Name`" => "Middle_Name",
		"`Shortlisted_Applicant_Details`.`Last_Name`" => "Last_Name",
		"`Shortlisted_Applicant_Details`.`Level_of_Education`" => "Level_of_Education",
		"if(`Shortlisted_Applicant_Details`.`DOB`,date_format(`Shortlisted_Applicant_Details`.`DOB`,'%m/%d/%Y'),'')" => "DOB",
		"`Shortlisted_Applicant_Details`.`Age`" => "Age",
		"`Shortlisted_Applicant_Details`.`District_of_Origin`" => "District_of_Origin",
		"`Shortlisted_Applicant_Details`.`Recruitment_centre`" => "Recruitment_centre",
		"`Shortlisted_Applicant_Details`.`Gender`" => "Gender",
		"`Shortlisted_Applicant_Details`.`Telephone_Contact`" => "Telephone_Contact",
		"`Shortlisted_Applicant_Details`.`Religion`" => "Religion",
		"`Shortlisted_Applicant_Details`.`Nationality`" => "Nationality",
		"`Shortlisted_Applicant_Details`.`NIN`" => "NIN",
		"`Shortlisted_Applicant_Details`.`Tribe`" => "Tribe",
		"`Shortlisted_Applicant_Details`.`Special_attribute`" => "Special_attribute",
		"`Shortlisted_Applicant_Details`.`OLevel_School`" => "OLevel_School",
		"`Shortlisted_Applicant_Details`.`English_Grade`" => "English_Grade",
		"`Shortlisted_Applicant_Details`.`Math_Grade`" => "Math_Grade",
		"`Shortlisted_Applicant_Details`.`Description`" => "Description",
		"`Shortlisted_Applicant_Details`.`Total_Mark`" => "Total_Mark",
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Shortlisted_Applicant_Details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Shortlisted_Applicant_Details_view.php";
	$x->RedirectAfterInsert = "Shortlisted_Applicant_Details_view.php?SelectedID=#ID#";
	$x->TableTitle = "Shortlisted Applicant Details";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`Shortlisted_Applicant_Details`.`Serial_Number`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("S/No", "Shortlist date", "First Name", "Middle Name", "Last Name", "Level of Education", "DOB", "Age", "District of Origin", "Recruitment centre", "Gender", "Telephone Contact", "Religion", "Nationality", "NIN", "Tribe", "Special attribute", "OLevel School", "English Grade", "Math Grade", "Description", "Total Mark");
	$x->ColFieldName = array('Serial_Number', 'Shortlist_date', 'First_Name', 'Middle_Name', 'Last_Name', 'Level_of_Education', 'DOB', 'Age', 'District_of_Origin', 'Recruitment_centre', 'Gender', 'Telephone_Contact', 'Religion', 'Nationality', 'NIN', 'Tribe', 'Special_attribute', 'OLevel_School', 'English_Grade', 'Math_Grade', 'Description', 'Total_Mark');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Shortlisted_Applicant_Details_templateTV.html';
	$x->SelectedTemplate = 'templates/Shortlisted_Applicant_Details_templateTVS.html';
	$x->TemplateDV = 'templates/Shortlisted_Applicant_Details_templateDV.html';
	$x->TemplateDVP = 'templates/Shortlisted_Applicant_Details_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';
	$x->HasCalculatedFields = false;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))) { $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Shortlisted_Applicant_Details`.`Serial_Number`=membership_userrecords.pkValue and membership_userrecords.tableName='Shortlisted_Applicant_Details' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Shortlisted_Applicant_Details`.`Serial_Number`=membership_userrecords.pkValue and membership_userrecords.tableName='Shortlisted_Applicant_Details' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3) { // view all
		// no further action
	}elseif($perm[2]==0) { // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Shortlisted_Applicant_Details`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Shortlisted_Applicant_Details_init
	$render=TRUE;
	if(function_exists('Shortlisted_Applicant_Details_init')) {
		$args=array();
		$render=Shortlisted_Applicant_Details_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Shortlisted_Applicant_Details_header
	$headerCode='';
	if(function_exists('Shortlisted_Applicant_Details_header')) {
		$args=array();
		$headerCode=Shortlisted_Applicant_Details_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode) {
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Shortlisted_Applicant_Details_footer
	$footerCode='';
	if(function_exists('Shortlisted_Applicant_Details_footer')) {
		$args=array();
		$footerCode=Shortlisted_Applicant_Details_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode) {
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>